---
- name: Baixando .deb do zabbix
  get_url:
    url: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb
    dest: /tmp

- name: Instalando arquivo zabbix-release_6.4-1+debian11_all.deb
  apt:
    deb: /tmp/zabbix-release_6.4-1+debian11_all.deb
  become: true

- name: Atualizar lista de pacotes
  apt:
    update_cache: yes
  become: true

- name: 'Instalando: zabbix-server-mysq, zabbix-frontend-php, zabbix-apache-conf, zabbix-sql-scripts e zabbix-agent'
  apt:
    name: ['zabbix-server-mysql', 'zabbix-frontend-php', 'zabbix-apache-conf', 'zabbix-sql-scripts', 'zabbix-agent']
    state: present
  become: true

- name: Habilitando zabbix-server
  service:
    name: zabbix-server
    enabled: yes
  become: true

- name: Habilitando zabbix-agent
  service:
    name: zabbix-agent
    enabled: yes
  become: true

- name: Habilitando apache2
  service:
    name: apache2
    enabled: yes
  become: true

- name: Criando banco de dados Zabbix
  mysql_db:
    name: zabbix
    state: present
  become: true

- name: Criando usuários zabbix para o banco zabbix
  mysql_user:
    login_user: root
    name: zabbix
    password: zabbix
    priv: zabbix.*:ALL
    state: present
    host: localhost
  become: true
  notify:
  - restart mysql

- name: Configurando variável global log_bin_trust_function_creators para 1
  mysql_variables:
    variable: log_bin_trust_function_creators
    value: 1
  become: true
  notify:
  - restart mysql

- name: Importando banco de dados
  mysql_db:
    name: zabbix
    state: import
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  #shell:
  #  cmd: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p zabbix
  become: true

- name: Configurando variável global log_bin_trust_function_creators para 0
  mysql_variables:
    variable: log_bin_trust_function_creators
    value: 0
  become: true
  notify:
  - restart mysql  
  
- name: Finalizando as configurações
  template:
    src: zabbix.j2
    dest: /etc/zabbix/zabbix_server.conf
  become: true
  notify:
    - restart apache2
    - restart mariadb
    - restart zabbix-server