---
- name: restart apache2 
  service:
    name: apache2
    state: restarted
  become: true

- name: restart zabbix-server 
  service:
    name: zabbix-server
    state: restarted
  become: true

- name: restart mariadb
  service:
    name: zabbix-server
    state: restarted
  become: true